import tensorflow as tf

DAYS = 9
FEATURE_SIZE = 4
THRESHOLD = 0.2
N_INPUT = FEATURE_SIZE * DAYS
N_LABEL = 3
N_HIDDEN_LAYER = 32
N_HIDDEN_UNIT = 16
LEARNING_RATE = 0.001
BATCH_SIZE = 128
MAX_EPOCH = 10000
ACTIVATION = tf.nn.relu
KEEP_PROB = 0.8

ROOT_PATH = "/home/liuzhf/workspace/projects/Toothless"
SUMMARY_DIR = ROOT_PATH + '/summary'
TRAIN_SUMMARY_DIR = SUMMARY_DIR+"/train"
CV_SUMMARY_DIR = SUMMARY_DIR+"/cv"
TEST_SUMMARY_DIR = SUMMARY_DIR+"/test"
CKPT_DIR = ROOT_PATH + '/model/future/by/{}/{}/{}/{}/'.format(DAYS, FEATURE_SIZE, N_HIDDEN_LAYER, N_HIDDEN_UNIT)
ACTUAL_CKPT_DIR = CKPT_DIR

TEST_DATA_SIZE = 2028

FIX_MISTAKE = True
FIX_MISTAKE_BY_DAY_THRESHOLD = False
FIX_MISTAKE_BY_ASSETS_THRESHOLD = False
