import tensorflow as tf

DAYS = 12
FEATURE_SIZE = 5
THRESHOLD = 0.15
N_INPUT = FEATURE_SIZE * DAYS
N_LABEL = 3
N_HIDDEN_LAYER = 10
N_HIDDEN_UNIT = 8
LEARNING_RATE = 0.001
BATCH_SIZE = 128
MAX_EPOCH = 10000
ACTIVATION = tf.nn.relu

SUMMARY_DIR = '../../summary'
TRAIN_SUMMARY_DIR = SUMMARY_DIR+"/train"
CV_SUMMARY_DIR = SUMMARY_DIR+"/cv"
TEST_SUMMARY_DIR = SUMMARY_DIR+"/test"
CKPT_DIR = './model/future/by/{}/{}/{}/'.format(FEATURE_SIZE, N_HIDDEN_LAYER, N_HIDDEN_UNIT)
ACTUAL_CKPT_DIR = CKPT_DIR

TEST_DATA_SIZE = 2004
